### ISSUE TITLE
Chromeでクッキー取得ができない

### ISSUE THREAD

**Issue by hokkaman** [xtne6f/NicoJK#1]
Chrome Ver80ぐらいからクッキーの仕様が変わったらしくクッキー取得ができなくなっています。

現状TvRemoteViewer_VB作者の対策ツールを噛まさないとChromeクッキーでログインできません。
http://vb45wb5b.seesaa.net/#NicoCookie4Chrome

ネイティブでログインできるように対応いただけたら幸いです。

参考になるかわかりませんが5chにクッキーデコードするPythonスクリプトがあるので貼り付けておきます。
http://mevius.5ch.net/test/read.cgi/avi/1485249966/958

よろしくおねがいします。

**Comment by xtne6f** [comment]
ありがとうございます。
最近はログインツールのほうを使っていてクッキー側ノーチェックでした。
参考のPythonスクリプトやその他情報をもとに更新しました。

こちらはMS-Edgeで動作確認しましたがChromeでは未確認のため、そちらでも確認してもらえると嬉しいです。
(今のEdgeはChromeと双子みたいなもんなので、おそらく問題ないと予想しますが…)

**Comment by xtne6f** [comment]
あと、設定ファイルの`execGetV10Key`の例では`jq`コマンドを使っていますが、jsonをパースできればなんでも良いです。
`.os_crypt.encrypted_key`自体はそう変わるものでもないでしょうから、
その値をメモ帳でコピペして`execGetV10Key="cmd /c echo {ここにコピペ}"`でも良いです。

**Comment by hokkaman** [comment]
ご対応ありがとうございました。
Chrome Ver86で試してみましたが無事取得できるようになりました。

迅速なご対応感謝いたします！！
