### ISSUE TITLE
[Question] ソースコードのライセンスについて

### ISSUE THREAD

**Issue by noriokun4649** [xtne6f/NicoJK#5]
はじめまして

本リポジトリのソースコードのライセンスについてお聞かせ願いたいのですが、ライセンス等ソースコードを利用する上での取り決めなどは何か決められていますでしょうか？　MITライセンスのプロジェクトにて利用させて頂きたいと考えております。

以上、よろしくお願いします。

**Comment by xtne6f** [comment]
ライセンスに関してはいちど @rutice 氏に伺ってみることをお勧めします。
純粋に私が記述した部分についてはもちろん利用してもらって構いませんが、rutice 氏の記述部分と不可分な部分も多いと思います。フォークの立場としてこちらは rutice 氏の決定に従います。
現状はライセンス条文などはなさそうなので、ソースコードの扱いについては宙ぶらりんです。

https://github.com/rutice/NicoJK にissueを開いて返答を少し待ってみて、もしも返答ないのであれば、クローズドな利用をしない限り拒否されることはないだろうと思います。

**Comment by noriokun4649** [comment]
さっそくのお返事ありがとうございます。

そうしてみることにします。こちらのissueは閉じさせていただきます。
