### ISSUE TITLE
【機能要望】過去ログ取得機能 (https://jikkyo.tsukumijima.net/)

### ISSUE THREAD

**Issue by hokkaman** [xtne6f/NicoJK#7]
NicoJKいつも利用させていただいています。
NicoJKの機能について1点要望させていただきます。

つくみ島氏よりニコニコ実況の過去ログがAPIとして提供されています。
https://jikkyo.tsukumijima.net/

現状のNicoJKの機能に過去ログ再生機能は実装されているものの、
ローカルで保管しているコメントしか読み込むことができないと存じています。

コメントファイルがローカルに存在しない場合に過去ログAPIを通して
過去ログコメントの取得機能を実装可能でしょうか。

TVTCommentの過去ログ取得機能が本件要望の機能に当たります。

ご多忙とは存じますがご検討の程よろしくお願いいたします。

**Comment by xtne6f** [comment]
この件、NicoJK自体には実装せずに[新しいプラグイン]( https://github.com/xtne6f/NXKakolog )を作りました。
今のところ取得時に手動または最低でもワンクリック必要ですが、おおむね要望の動作を実装できているはずです。

個人的な事情ですが、過去ログAPIに頼る機会が自分は「在京局と地方局とで放送時刻が異なる番組を取得」するときぐらいしかないので、放送時刻と同じ時刻の実況を自動取得できてもあまり嬉しくないためです（同じ時刻の実況は予約と一緒に保存されるため）。

**Comment by hokkaman** [comment]
ご対応ありがとうございました。
早速導入させていただき問題なく動作できました。

過去ログ取得が楽になるのでとてもありがたいです。

自動取得に対するお考えについては承知いたしました。
